language: python
python:
- '2.7'
install:
- pip install -U platformio
script:
- platformio run
deploy:
  provider: releases
  api_key:
    secure: Gnwgg9O+qL0WC4Mwrb6KP2aGBEnfjTrKWZlaoPAieMQK82DH0ObwgWsEdTu6CXQUZphEQXoGyvHLkSJqgbmQ2oNh8C1SM+KWKyMeL3s/SudBfCmmzANphwhP+GPoAd190XsoDL5Hk07Jo+MtxKZXB4RpBZgx9aRFzdgbB/Wol/Ys0v4kbE+JgpPUa024tMPH+1KOmfw7cUKlqJWXBS1R5hV7dA7z5bHMBMqe/RN5PgFmkmWNep3t2czPdvkah8IIJubPgeeBz4wxcaF6wujXu6mjAIRcHAMxHnzQCfp/0Z1OZwuAbMTt1VoG0iMyTNDbSJwnECvAYoUVCfjw6Pk1n5paxejrBWHhoDqb7wzBrK8g5j/YXXE0ijLdrIgPzgVJtXI5ws9ZKZ9cGUVcx79C5FcBTyYWj7cSpP6/n6BgD0Q+LnqoQF5GpJdLU5YRIMlixzqKUYcffNlYmOvV7ytPckZNa0Vdc8Mtse0+WgHxBTIBMktFfNGS0qHfNaS6bcKX9DhhmulpeaCPNGSZxLFYS9t6gDBgiunk4aTtGLfGu+VObGCaOLhEsmN2fK9UTLvM3lQeiWZYtxztIUFLYjp61Bxu2AI7G65DbiCyvt983SaQa63qqc3Knwb+tC0kvySDgcBT10XN9l/FDelRfC8BRbL6YQnb8iI5z+H/9yVYss4=
  file: ".pioenvs/nodemcuv2/firmware.bin"
  on:
    repo: cwi-dis/iotsaSmartMeter
    tags: true
    all_branches: true
